FROM golang:1.17-alpine as build-env

# make current working directory /app
WORKDIR /go/src/cms.csesoc.unsw.edu.au
RUN go get github.com/githubnemo/CompileDaemon

EXPOSE 8080

# export environment variable for gopath
ENV GOPATH /go

# might start the app
#CMD ["go", "run", "main.go"]

ENTRYPOINT CompileDaemon --build="go build main.go" --command="./main"